### ISSUE TITLE
Explain README example purpose

### ISSUE THREAD

**Issue by shamrin** [altendky/qtrio#205]
>  The first example here shows classic pure Qt code.

It would be nice to have a short explanation of what the example is trying to accomplish. For those unfamiliar with Qt :)

**Comment by altendky** [comment]
Sounds like a good idea, thanks.  It also makes me think that I should review and make sure the readme clearly states that QTrio is not going to provide docs for understanding Qt (and maybe even pick some relevant intro documentation and tutorials to link to).
