### ISSUE TITLE
Callback-style into a 'global' nursery (or something) (maybe)

### ISSUE THREAD

**Issue by altendky** [altendky/qtrio#57]
Just something more akin to what people expect in a Qt application.

**Comment by altendky** [comment]
https://github.com/innodatalabs/triq/ does this

**Comment by altendky** [comment]
Just off the top of my head...

```python
with qtrio.open_emissions_nursery(until=the_widget.closed) as diaper:
    diaper.connect(a_button.clicked, an_async_def)
```

(nursery emissions?  diaper? ...  sorry)

**Comment by altendky** [comment]
@mkroutikov, #90 isn't exactly what you had so maybe you could weigh in on it.  I wanted to stay away from globals and allow it to be used multiple times for whatever level of granularity people wanted in their emissions buckets.

@nicoddemus, likewise...  let me know if this is going where you were asking about.

**Comment by altendky** [comment]
I'm going to move forward with the PR.  I am interested in having things reviewed and I am happy to wait for it but since QTrio is just getting started I don't know when I should be waiting or not.  If you are looking to be involved just let me know what pace to plan on.  And of course, being merged doesn't mean things can't change.  `:]`

**Comment by mkroutikov** [comment]
This is sufficient for my immediate purposes, thank you. See sketch there:
https://github.com/innodatalabs/triq/issues/5

I am still trying to wrap my mind around fine-grained design of the `open_emissions_nursery`, not sure I understand the use case. But, again, I am focused on legacy Qt apps and want an incremental way to introduce async code there. When writing from scratch, using all-async code should open new ways of shaping the ui code (as opposed to signal handlers, sync or async).
Would be nice to see a sketch of such an app.

**Comment by altendky** [comment]
That'd be [`qtrio.enter_emissions_channel()`](https://qtrio.readthedocs.io/en/v0.1.0/core.html#emissions).  But sure, seeing a real application using this would be nice...  `:]` at present this 'structured GUI concurrency' plan is nothing beyond a theory with a lib that'll let you attempt it.  I can't even say I've done a real program with Trio yet.  I'm basically just trying to make sure to use their basic patterns when I'm implementing the Qt stuff.  This way we end up with a Trio program that happens to do a little 'I/O with the user via widgets'.  Time will tell if that's silly but each layer is optional.  You can do whatever you want with the core `qtrio.Runner`.

**Comment by nicoddemus** [comment]
Sorry for answering so late!

>  I am focused on legacy Qt apps and want an incremental way to introduce async code there. 

Indeed that's my initial focus too, being able to plug "async" slots into an existing application.

Saw this example:

```python
with qtrio.open_emissions_nursery(until=the_widget.closed) as diaper:
    diaper.connect(a_button.clicked, an_async_def)
```

And noticed that it was already on `master`, so I managed to create this example which fits my initial use case nicely:

```python
import trio
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout

import qtrio


class MyWidget(QWidget):

    def __init__(self):
        super().__init__()
        self.button = QPushButton()
        self.button.setText("Exit")
        layout = QVBoxLayout(self)
        layout.addWidget(self.button)

        self.resize(200, 200)

        connect(self.button.clicked, self.slot_clicked)

    async def slot_clicked(self, x):
        await trio.sleep(1.0)
        print("hello")
        await trio.sleep(1.0)
        print("bye")


_nursery: qtrio.EmissionsNursery = None


def connect(signal, async_func):
    _nursery.connect(signal, async_func)


async def main():
    qapp = QApplication.instance()
    assert qapp is not None

    global _nursery

    async with qtrio.open_emissions_nursery(until=qapp.lastWindowClosed) as nursery:
        _nursery = nursery

        main_widget = MyWidget()
        main_widget.show()


if __name__ == "__main__":  # pragma: no cover
    qtrio.run(main)
```

Nevermind the ugly global to avoid carrying the nursery everywhere, but it is impressive what is possible already. Great work @altendky!

**Comment by nicoddemus** [comment]
Oh just now I saw https://github.com/innodatalabs/triq/issues/5 which is basically what I posted above. 🤦‍♂️
