### ISSUE TITLE
Sometimes have open_emissions_channel manage the read channel context

### ISSUE THREAD

**Issue by altendky** [altendky/qtrio#62]
```python
async with qtrio.open_emissions_channel(signals=[a_signal]) as emissions:
    async with emissions.channel:
        async for emissions in emissions.channel:
            print(emissions)
```

would often rather be just

```python
async with qtrio.open_emissions_channel(signals=[a_signal]) as emissions:
    async for emissions in emissions.channel:
        print(emissions)
```

Maybe just separate function names to do each?  Or even...

```python
async for emissions in qtrio.open_emissions_channel(signals=[a_signal]):
    print(emissions)
```

**Comment by richardsheridan** [comment]
Just my opinion but I thought examples/emissions.py would look better as:

```
    async with qtrio.open_emissions_channel(signals=signals) as channel:
        window.show()
        async for emission in emissions.channel:
            if emission.is_from(window.decrement.clicked):
                 ...
```

I think that moment to initialize things, or maybe pass the channel around, before iterating could be valuable.

**Comment by altendky** [comment]
True, setup/show/iterate is important.

**Comment by altendky** [comment]
I'm trying to think through the setup and teardown here a bit more.  The context managers for send and receive channels are pretty trivial.  They return the channel itself on entry and await `.aclose()` on exit.  Repeated calls to `.aclose()` just checkpoint. Let's consider the following shutdown process.

1. Close the send channel
   - This is a single call (well, whatever it does inside...) that will cut off all signal emissions from being collected in one go.
   - Since the signals are still connected, if they can get triggered between the close and them being disconnected then we'll get a `trio.ClosedResourceError` in the callback.  Easy enough to throw away.
2. Disconnect the signals
3. Close the receive
    - If there are no remaining emissions to collect
        - This makes it so we would get a `trio.ClosedResourceError` if we try to use the receive channel as opposed to `trio.EndOfChannel` if we didn't close.
    - If there were remaining emissions to collect
        - Then attempting to receive will get the `trio.ClosedResourceError` instead of getting an item.

https://trio.readthedocs.io/en/stable/reference-core.html?highlight=open_memory_channel#channel-shutdown

Ok, so why close the receiver?  We are already closing the sender and disconnecting the signals...  so we won't be piling more into the buffer.  I suppose it could still clear the buffer and free up some memory potentially which is probably a good default.  And `open_emissions_channel()` can remain for the special cases where you want to iterate post-collection rather than during collection.

Hmm, so the only async thing in `open_emissions_channel()` is the `async with send_channel:`.  The signal connections etc are all sync.  So perhaps it should be broken down along those lines?  `open_emissions_channel()` turns to sync for use only in 'special' cases and you are responsible for any channel closure you want.  That is the 'not super careful but you are not required to close the channels anyways' option while `enter_emissions_channel()` is async and fully manages both receive and send channels as per the list above.

Thoughts?  Did I miss something big again?  I'll put together a separate PR at some point for this new approach so we can look at it.

**Comment by richardsheridan** [comment]
One more thought, what's the purpose of revising the send channel? It seems like that could stay hidden to the user.

**Comment by altendky** [comment]
Just exploring. Wondering if a useful separation between the two would be 'sync and fully manual' vs 'async and fully automatic'.  The `.aclose()` on `Emissions` only closing one channel struck me as a bit odd too.  But I haven't made it back to reviewing the PR yet to see what effect this had...

**Comment by altendky** [comment]
So I tried to expand your suggestion to a grand plan...  Yes, I think we want a version that manages both the send and receive channels.  We may want more, but it doesn't need to muddy up this addition.

Just to write it down, I've only come up with two concerns about always using the fully managed solution.  First is that you may want to process emissions after exiting.  This could be addressed with an explicit send channel close call and something like `rest_of_the_emissions = await emissions.create_list()` inside the context.  The second is that there may be cases where you want to close a channel early and are concerned about the performance of closing and checkpointing a second time when leaving the overall context.  Not something to prioritize at this point and easily added (back) later.

Since `trio.open_memory_channel()` doesn't manage either channel I think it is important to have a different name for a 'similar' thing that does manage the channels.  This means that even if only one emissions function is retained long term that I think it will be the `enter_emissions_channel()` one.  Adding it here, as opposed to changing the existing functionality and keeping the `open_emissions_channel()` name, seems more proper.

Oh yeah, why add the `Emissions.send_channel` attribute?  Maybe I was jumping ahead.  Regardless, it doesn't seem helpful to hold just a method of the object rather than the object itself.  Maybe it should be private, as you mentioned.  I wasn't worrying _too_ terribly much about that yet.  Hence the various warnings about a quick breaking interface.

Sorry if I'm rambling.  I'm no API design expert so I'm trying to write out my thoughts both for myself and in case they help anyone help me learn.  Anyways, a new and more focused PR is on the way.
